version: '3.4'
services:

  mariadb: 
    image: mariadb 
    restart: unless-stopped 
    expose: 
     - "11012:3306"
    volumes:
     - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Msql_1&2
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: Msql_1&2
    command: [--transaction-isolation=READ-COMMITTED,--binlog-format=ROW,--innodb-file-per-table=1,--skip-innodb-read-only-compressed]
    # to avoid innodb bugs

  redis:
    image: redis
    restart: unless-stopped
    expose:
     - "11011:6379"
    volumes:
     - ./cache:/data
    command: redis-server --requirepass 'redis_password'

  nextcloud:
    image: nextcloud:fpm
    restart: unless-stopped
    expose:
     - "11010:9000"
    volumes:
     - ./nextcloud/html:/var/www/html
     - ./nextcloud/data:/var/www/html/data
     - ./nextcloud/config:/var/www/html/config
     - ./nextcloud/custom_apps:/var/www/html/custom_apps
    links:
     - mariadb:mariadb
     - redis:redis
    depends_on:
     - mariadb
     - redis
